package constants

import (
	"cloud.google.com/go/vision/v2/apiv1/visionpb"
)

var FeatureList = []*visionpb.Feature{
	// type unspecified
	{
		Type:       visionpb.Feature_TYPE_UNSPECIFIED,
		MaxResults: 1,
	},
	// face detection
	{
		Type:       visionpb.Feature_FACE_DETECTION,
		MaxResults: 1,
	},
	// landmark
	{
		Type:       visionpb.Feature_LANDMARK_DETECTION,
		MaxResults: 1,
	},
	// logo
	{
		Type:       visionpb.Feature_LOGO_DETECTION,
		MaxResults: 1,
	},
	// label
	{
		Type:       visionpb.Feature_LABEL_DETECTION,
		MaxResults: 1,
	},
	// text
	{
		Type:       visionpb.Feature_TEXT_DETECTION,
		MaxResults: 1,
	},
	//doc text
	{
		Type:       visionpb.Feature_DOCUMENT_TEXT_DETECTION,
		MaxResults: 1,
	},
	// safe search
	{
		Type:       visionpb.Feature_SAFE_SEARCH_DETECTION,
		MaxResults: 1,
	},
	// image properties
	{
		Type:       visionpb.Feature_IMAGE_PROPERTIES,
		MaxResults: 1,
	},
	// crop hints
	{
		Type:       visionpb.Feature_CROP_HINTS,
		MaxResults: 1,
	},
	// web detection
	{
		Type:       visionpb.Feature_WEB_DETECTION,
		MaxResults: 1,
	},
	// product search
	{
		Type:       visionpb.Feature_PRODUCT_SEARCH,
		MaxResults: 1,
	},
	// object localization
	{
		Type:       visionpb.Feature_OBJECT_LOCALIZATION,
		MaxResults: 1,
	},
}

var BlockedWordsMap = map[string]bool{
	"nude":              true,
	"naked":             true,
	"exposed":           true,
	"breasts":           true,
	"genitals":          true,
	"buttocks":          true,
	"intimate areas":    true,
	"undress":           true,
	"sexual parts":      true,
	"body":              true,
	"pornography":       true,
	"adult":             true,
	"sex":               true,
	"fetish":            true,
	"erotic":            true,
	"provocative":       true,
	"seductive":         true,
	"lewd":              true,
	"x-rated":           true,
	"suggestive":        true,
	"blood":             true,
	"gore":              true,
	"murder":            true,
	"assault":           true,
	"killing":           true,
	"brutality":         true,
	"attack":            true,
	"weapon":            true,
	"violence":          true,
	"torture":           true,
	"mutilation":        true,
	"wound":             true,
	"shoot":             true,
	"stab":              true,
	"fuck":              true,
	"bitch":             true,
	"slut":              true,
	"asshole":           true,
	"crap":              true,
	"damn":              true,
	"hell":              true,
	"cunt":              true,
	"bullshit":          true,
	"bastard":           true,
	"kill":              true,
	"hate":              true,
	"racist":            true,
	"bigotry":           true,
	"homophobic":        true,
	"extremist":         true,
	"terrorist":         true,
	"discrimination":    true,
	"xenophobia":        true,
	"hurt":              true,
	"cut":               true,
	"suicide":           true,
	"self-injury":       true,
	"pain":              true,
	"depressed":         true,
	"overdose":          true,
	"scar":              true,
	"drug":              true,
	"alcohol":           true,
	"cocaine":           true,
	"marijuana":         true,
	"heroin":            true,
	"smoking":           true,
	"substance":         true,
	"high":              true,
	"inject":            true,
	"dead":              true,
	"mutilated":         true,
	"graphic":           true,
	"horrific":          true,
	"disturbing":        true,
	"cadaver":           true,
	"body parts":        true,
	"wreckage":          true,
	"adult content":     true,
	"sexual":            true,
	"explicit":          true,
	"violent":           true,
	"brutal":            true,
	"risqué":            true,
	"racy":              true,
	"surgery":           true,
	"medical condition": true,
	"gun":               true,
	"knife":             true,
	"blade":             true,
	"bomb":              true,
	"firearm":           true,
	"bullet":            true,
	"rifle":             true,
	"pistol":            true,
	"terror":            true,
	"explosive":         true,
	"hostage":           true,
	"insurgent":         true,
	"radical":           true,
	"militant":          true,
	"abuse":             true,
	"exploitation":      true,
	"neglect":           true,
	"harm":              true,
	"kidnap":            true,
	"trafficking":       true,
	"pedophilia":        true,
	"abomination":       true,
	"accident":          true,
	"abuser":            true,
	"addiction":         true,
	"adultery":          true,
	"assaulted":         true,
	"axe":               true,
	"battered":          true,
	"betrayal":          true,
	"bloodshed":         true,
	"brutally":          true,
	"cannibalism":       true,
	"chaos":             true,
	"chemical":          true,
	"choking":           true,
	"crazed":            true,
	"crime":             true,
	"cruelty":           true,
	"cutting":           true,
	"death":             true,
	"deformed":          true,
	"dismembered":       true,
	"dismemberment":     true,
	"drugs":             true,
	"drowning":          true,
	"duel":              true,
	"execution":         true,
	"explosions":        true,
	"extremism":         true,
	"flesh":             true,
	"foul":              true,
	"freak":             true,
	"frightening":       true,
	"gang":              true,
	"gash":              true,
	"genocide":          true,
	"grave":             true,
	"gruesome":          true,
	"gunfire":           true,
	"gunshot":           true,
	"hacker":            true,
	"headshot":          true,
	"homicide":          true,
	"hostility":         true,
	"hunger":            true,
	"hurtful":           true,
	"incest":            true,
	"injury":            true,
	"insanity":          true,
	"killer":            true,
	"knives":            true,
	"laceration":        true,
	"lust":              true,
	"machete":           true,
	"madness":           true,
	"malice":            true,
	"manslaughter":      true,
	"mental illness":    true,
	"murderous":         true,
	"necrophilia":       true,
	"negligence":        true,
	"nihilism":          true,
	"obscene":           true,
	"offensive":         true,
	"outrage":           true,
	"panic":             true,
	"panic attack":      true,
	"pedophile":         true,
	"pervert":           true,
	"poison":            true,
	"predator":          true,
	"prison":            true,
	"psycho":            true,
	"psychoactive":      true,
	"psychopath":        true,
	"rampage":           true,
	"rape":              true,
	"reckless":          true,
	"revenge":           true,
	"sadistic":          true,
	"sadism":            true,
	"scare":             true,
	"scary":             true,
	"scum":              true,
	"screaming":         true,
	"self-destructive":  true,
	"severed":           true,
	"shattered":         true,
	"slaughter":         true,
	"slaughtered":       true,
	"slur":              true,
	"suffocation":       true,
	"suicide attempt":   true,
	"suffering":         true,
	"terrorism":         true,
	"threat":            true,
	"torturer":          true,
	"toxic":             true,
	"trauma":            true,
	"trigger":           true,
	"turbulence":        true,
	"twisted":           true,
	"vandalism":         true,
	"victim":            true,
	"violently":         true,
	"vomit":             true,
	"war":               true,
	"warfare":           true,
	"wicked":            true,
	"wounded":           true,
	"wreck":             true,
	"wrath":             true,
	"youth violence":    true,
}

